### ISSUE TITLE
Temperature and dewpoint are celsius only

### ISSUE THREAD

**Issue by jds11111** [mawinkler/astroweather#18]
Do these entities not have `device_class: temperature` ?

**Comment by mawinkler** [comment]
They do
`
state_class: measurement
attribution: Powered by 7Timer
unit_of_measurement: °C
device_class: temperature
icon: mdi:thermometer
friendly_name: Astroweather 2m Temperature
`

**Comment by jds11111** [comment]
Oddly, the forecast temperature converts to the default units fine, but the current temp stays in deg C only.

**Comment by jds11111** [comment]
Oddly, the forecast temperature converts to the default units fine, but the current temp stays in deg C only.

**Comment by mawinkler** [comment]
Are you referring to the lovelace card? If so, this is now fixed with the latest [release](https://github.com/mawinkler/astroweather-card/releases/tag/v0.22.1)

**Comment by jds11111** [comment]
I saw that fix.  I make a plot with data scraped from different sources for a different dashboard card, and the astroweather one is the only one that stays in C:
![image](https://user-images.githubusercontent.com/15203860/180248705-484fb32e-39f7-4a76-a249-5f068ed636dd.png)

**Comment by MisterTFM** [comment]
> Are you referring to the lovelace card? If so, this is now fixed with the latest [release](https://github.com/mawinkler/astroweather-card/releases/tag/v0.22.1)

Thanks for correcting the Lovelace card, it now displays in F and MPH.

**Comment by mawinkler** [comment]
For the sun, I'm calculating the twilights for the center of the object not for the upper edge as some do. This matches with Stellarium and SkySafari 6 Pro.

In regards to the unit conversion, I just pushed 0.22.2 which should resolve the issue. I didn't create a release yet, so you would need to redownload astroweather from the main branch.

**Comment by jds11111** [comment]
That fixed it!  The units are now corrected on all the cards.  Many thanks.

**Comment by mawinkler** [comment]
thank you for reporting back 🎉

**Comment by MisterTFM** [comment]
> However, it still shows precipitation rate in mm/hour vs. inches/hour

I'm still seeing percipitation rate in mm/hr vs. inches/hour.
![ScreenHunter 371](https://user-images.githubusercontent.com/74779407/180516455-7146efb6-b0f8-4623-b001-8eb68976d821.jpg)

**Comment by mawinkler** [comment]
This is because the text is currently defined in constants. I will add that to my to-do list for later. [This](https://github.com/mawinkler/astrolive) is what I'm working on now.
