### ISSUE TITLE
The astroweather custom integration is using deprecated weather forecast

### ISSUE THREAD

**Issue by Akinetopsia1** [mawinkler/astroweather#50]
⚠ **This stops working in version 2024.3.0. Please address before upgrading.**

The custom integration astroweather implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

Please create a bug report at https://github.com/mawinkler/astroweather/issues.

Once an updated version of astroweather is available, install it and restart Home Assistant to fix this issue.

**Comment by Akinetopsia1** [comment]
Also of note the "show graphs" option hasn't been working in probably a year. It just shows a blank area where they should be

![image](https://github.com/mawinkler/astroweather/assets/106173717/e6a2d5e6-e249-45b9-afd5-716e9d8a0c7d)

**Comment by mawinkler** [comment]
Please open separate issues for different topics.

The first was fixed in Sept. '23 with version [v0.23.2](https://github.com/mawinkler/astroweather/compare/v0.23.1...v0.23.2).

Second, maybe you're using an outdated version? See above.

**Comment by gmorain** [comment]
Hi, new atroweather user here (so using the latest release): graphs are displayed without a problem on my Raspberry Pi 3 based HA setup

**Comment by Akinetopsia1** [comment]
My bad, i forgot that the HACS addons updates were separate.

It fixed the warning, however i still have the graph issue. i'll open a new issue and close this one.
